### ISSUE TITLE
Not sure if this is the right place to put this.

### ISSUE THREAD

**Issue by Fishbowlkraken** [nick-parker/Bread#6]
However, when I try to open this in Ubuntu, it just crashes immediately. Here's the output of the terminal when I try to run it. Is there something I can do to make this work? I noticed a .dll file in the main folder, so is this a Windows only program? If so, sorry about posting this question, since obviously it won't work for me.

`'/home/xakh/Downloads/Bread-master/Bread.jar'
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
    at main.Run.main(Run.java:21)
    ... 5 more
`

**Comment by nick-parker** [comment]
I develop on Ubuntu, but I haven't tried running from the .jar in a while. It's possible that's still configured to use the .dll file. I'll look into it.

**Comment by Fishbowlkraken** [comment]
How exactly do I run it if not from the .jar? I'm not sure how it works.

**Comment by nick-parker** [comment]
You can also pull up all the code in an IDE and run from Run.java. However, I just reexported the .jar and confirmed it works with Java 1.8.0_91 in Ubuntu. Specifically, java -jar Bread.jar Prints/wave.stl Prints/wavesurface.stl config.txt output results in a new gcode file output.g which appears correct in Repetier.

**Comment by nick-parker** [comment]
@Fishbowlkraken could you try this again with the latest .jar file? 

There's a couple possible problems:
- The way you worded your issue, it sounds like you're trying to run this as an interactive program? Bread currently only has a command line interface - see the Getting Started section of the readme.
- You may be on an old Java version. Parts of this project require JDK 1.8. The readme didn't specify that until today though, so you can hardly be blamed if this is the case.

**Comment by Fishbowlkraken** [comment]
Sure, sorry, I didn't realize this didn't have a graphical interface to it,
so I was honestly a bit intimidated by trying to run it again, as I'm
pretty rusty on command line applications.
